/**
 * PDF Export Utility — Generate PDF from the roadmap results.
 * 
 * Uses html2canvas + jsPDF to capture the dashboard and export as PDF.
 */

import html2canvas from 'html2canvas'
import jsPDF from 'jspdf'

/**
 * Export the results dashboard as a PDF document.
 */
export async function exportRoadmapPDF(result) {
  const { profile, gap_summary, roadmap } = result

  const pdf = new jsPDF('p', 'mm', 'a4')
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 15
  let y = 20

  // ─── Header ────────────────────────────────────
  pdf.setFontSize(22)
  pdf.setTextColor(59, 130, 246)
  pdf.text('SkillForge', margin, y)
  pdf.setFontSize(10)
  pdf.setTextColor(148, 163, 184)
  pdf.text('AI-Adaptive Learning Roadmap', margin + 55, y)
  y += 12

  // Line separator
  pdf.setDrawColor(59, 130, 246)
  pdf.setLineWidth(0.5)
  pdf.line(margin, y, pageWidth - margin, y)
  y += 10

  // ─── Profile Summary ──────────────────────────
  pdf.setFontSize(14)
  pdf.setTextColor(30, 41, 59)
  pdf.text('Profile Summary', margin, y)
  y += 8

  pdf.setFontSize(10)
  pdf.setTextColor(71, 85, 105)
  pdf.text(`Experience Level: ${profile?.experience_level || 'N/A'}`, margin, y)
  y += 6
  pdf.text(`Match Percentage: ${Math.round(profile?.match_percentage || 0)}%`, margin, y)
  y += 6
  pdf.text(`Skills Matched: ${gap_summary?.matched_count || 0} / ${gap_summary?.total_required || 0}`, margin, y)
  y += 6
  pdf.text(`Estimated Learning Time: ${gap_summary?.estimated_total_hours || 0} hours`, margin, y)
  y += 6

  const criticalMissing = (gap_summary?.critical_missing || []).join(', ')
  if (criticalMissing) {
    pdf.setTextColor(220, 38, 38)
    pdf.text(`Critical Missing Skills: ${criticalMissing}`, margin, y)
    pdf.setTextColor(71, 85, 105)
  }
  y += 12

  // ─── Roadmap Mode ──────────────────────────────
  pdf.setFontSize(14)
  pdf.setTextColor(30, 41, 59)
  pdf.text(`Learning Path (${roadmap?.mode || 'standard'} mode)`, margin, y)
  y += 10

  // ─── Modules ───────────────────────────────────
  const allModules = roadmap?.phases?.flatMap(p => p.modules) || []

  allModules.forEach((mod, i) => {
    // Check if we need a new page
    if (y > 260) {
      pdf.addPage()
      y = 20
    }

    // Module header
    pdf.setFontSize(11)
    pdf.setTextColor(30, 41, 59)
    const diffColor = {
      beginner: [34, 197, 94],
      intermediate: [245, 158, 11],
      advanced: [239, 68, 68],
    }
    const dc = diffColor[mod.difficulty] || [100, 100, 100]
    pdf.setTextColor(...dc)
    pdf.text(`-`, margin, y)
    pdf.setTextColor(30, 41, 59)
    pdf.text(`${i + 1}. ${mod.skill}`, margin + 5, y)

    pdf.setFontSize(9)
    pdf.setTextColor(148, 163, 184)
    pdf.text(`${mod.difficulty} | ${mod.estimated_hours}h`, margin + 100, y)
    y += 5

    // Course info
    if (mod.course) {
      pdf.setFontSize(9)
      pdf.setTextColor(59, 130, 246)
      pdf.text(`  > ${mod.course.title} (${mod.course.platform})`, margin + 5, y)
      y += 5
    }

    if (mod.related_resources && mod.related_resources.length > 0) {
      pdf.setFontSize(8)
      pdf.setTextColor(236, 72, 153) // Pinkish for curated resources
      pdf.text(`  > Resource: ${mod.related_resources[0].title}`, margin + 5, y)
      y += 5
    }

    // Reasoning (short)
    if (mod.reasoning) {
      pdf.setFontSize(8)
      pdf.setTextColor(148, 163, 184)
      const why = mod.reasoning.why_needed || ''
      const truncated = why.length > 90 ? why.substring(0, 90) + '...' : why
      pdf.text(`  ${truncated}`, margin + 5, y)
      y += 7
    }
  })

  // ─── Footer ────────────────────────────────────
  y += 5
  if (y > 260) { pdf.addPage(); y = 20 }
  pdf.setDrawColor(200, 200, 200)
  pdf.line(margin, y, pageWidth - margin, y)
  y += 6
  pdf.setFontSize(8)
  pdf.setTextColor(148, 163, 184)
  pdf.text('Generated by SkillForge — AI-Adaptive Onboarding Engine', margin, y)
  pdf.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth - margin - 40, y)

  // Save
  pdf.save('SkillForge_Learning_Roadmap.pdf')
}
